sudo: required
service:
      - docker

before_install:
        - docker build -t hotwing78/docker-react -f Dockerfile.dev .


script:
        - docker run htowing78/docker-react npm run test -- --coverage        
